Repository oveleon/contao-cookiebar, pull requests merged in 2024-04, with the labels that each got.

#201 Feature/hide cookiebar
  docs/CONFIGURATION.md
  src/EventListener/FrontendTemplateListener.php
  src/Resources/contao/classes/Cookiebar.php
  src/Resources/contao/dca/tl_cookiebar.php
  src/Resources/contao/dca/tl_page.php
  src/Resources/contao/languages/de/tl_cookiebar.xlf
  src/Resources/contao/languages/de/tl_page.xlf
  src/Resources/contao/languages/en/tl_cookiebar.xlf
  src/Resources/contao/languages/en/tl_page.xlf
  src/Resources/contao/languages/fr/tl_cookiebar.xlf
  src/Resources/contao/languages/fr/tl_page.xlf
  src/Resources/contao/languages/it/tl_cookiebar.xlf
  src/Resources/contao/languages/it/tl_page.xlf
  src/Resources/contao/languages/sv/tl_cookiebar.xlf
  src/Resources/contao/languages/sv/tl_page.xlf
  src/Resources/public/scripts/cookiebar.js
  src/Resources/public/scripts/cookiebar.min.js
Labels: enhancement

#203 Word-spacing on `body` breaks the cookiebar position
  gulpfile.js
  package.json
  src/Resources/public/styles/_cookiebar.scss
  src/Resources/public/styles/cookiebar_default.css
  src/Resources/public/styles/cookiebar_simple.css
Labels: bug

#206 Properly load google consent mode in 1.x
  src/Resources/contao/classes/CookieConfig.php
Labels: bug

#205 Implement custom properties / Refactor cookiebar styles
  gulpfile.js
  src/Resources/public/styles/_cookiebar.scss
  src/Resources/public/styles/cookiebar_default.css
  src/Resources/public/styles/cookiebar_default.scss
  src/Resources/public/styles/cookiebar_simple.css
  src/Resources/public/styles/cookiebar_simple.scss
Labels: bug, enhancement
